AWSTemplateFormatVersion: '2010-09-09'
Description: 'Demoilua'
Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: '70'
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref JuusoSecurity1
  JuusoSecurity1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: vpc-7e1cd314
      GroupDescription: Sample source security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          SourceSecurityGroupId: !Ref JuusoSecurity2
  JuusoSecurity2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: vpc-7e1cd314
      GroupDescription: Sample target security group
  MyLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      Instances:
        [!Ref MyEC2Instance]
      AvailabilityZones:
        - "eu-central-1a"
      Listeners:
        - LoadBalancerPort: '80'
          InstancePort: '80'
          Protocol: HTTP
      SecurityGroups:
        - !Ref JuusoSecurity2
Outputs:
  LoadBalancerDNSAddress:
    Value: !GetAtt MyLoadBalancer.DNSName

