AWSTemplateFormatVersion: '2010-09-09'
Description: 'Demoilua'
Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: '70'
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref JuusoSecurity1
  JuusoSecurity1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: vpc-7e1cd314
      GroupDescription: Sample source security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          SourceSecurityGroupId: !Ref JuusoSecurity2
  JuusoSecurity2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: vpc-7e1cd314
      GroupDescription: Sample target security group
  MyLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
        - subnet-a31cabc9
        - subnet-8be20ff7
      SecurityGroups:
        - !Ref JuusoSecurity2
  Kuuntelija:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions:
        - Type: "redirect"
          RedirectConfig:
            Protocol: "HTTPS"
            Port: "443"
            Host: "#{host}"
            Path: "/#{path}"
            Query: "#{query}"
            StatusCode: "HTTP_301"
      LoadBalancerArn: !Ref MyLoadBalancer
      Port: 80
      Protocol: "HTTP"
  V2TG:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: "80"
      Protocol: "HTTP"
      VpcId: vpc-7e1cd314
Outputs:
  LoadBalancerDNSAddress:
    Value: !GetAtt MyLoadBalancer.DNSName

